fix: disable named tag with 'time'
openGemini/openGemini pull request #208
Opened 2023-04-17 14:47 UTC by xmh1011

### What problem does this PR solve?

Issue Number: fix #200 

### What is changed and how it works?
Please describe how it works
```
>>> insert mst,tag=1,time=12 f1=2
Elapsed: 12.85875ms  
ERR: {"error":"tag name can not be 'time'"}
```

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [ ] Test B
- [ ] Test cases to be added
- [ ] No code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-20 09:32 UTC, shilinlee requested changes

2023-04-23 06:25 UTC, fx408 requested changes

2023-04-24 05:51 UTC, xmh1011 commented on open_src/influx/meta/data.go
> +		if fieldToCreate[i].GetFieldName() == "time" {
已经改到在 writeHelper.updateSchemaIfNeeded 方法中提前判断

2023-04-24 06:41 UTC, shilinlee approved these changes

2023-04-24 06:43 UTC, merged