feat: Updated version to support branch display function
openGemini/openGemini pull request #269
Opened 2023-05-15 06:53 UTC by ganqiu

### What problem does this PR solve?

Issue Number: close/fix/resolve/ref #xxx

### What is changed and how it works?
Please describe how it works

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B
- [ ] Test cases to be added
- [ ] No code

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-15 07:41 UTC, shilinlee requested changes

2023-05-15 07:41 UTC, shilinlee commented on gobuild.txt
> +error
This is an accidentally uploaded file.

2023-05-15 07:41 UTC, shilinlee commented on app/ts-cli/main.go
> +const TsStore = "ts-cli"
This variable may be called `TsCli` more appropriate.

2023-05-15 07:41 UTC, shilinlee commented on app/ts-cli/main.go
> +	"runtime"
Packages import order should be like this:

```
Official Libraries/Built-in Packages


Three-party library
```

See [goimports-reviser](https://github.com/incu6us/goimports-reviser)

2023-05-15 09:11 UTC, ganqiu commented
> test example
![image](https://github.com/openGemini/openGemini/assets/112836415/6943cba5-449f-44ce-9e75-98cb7fb41e02)
![image](https://github.com/openGemini/openGemini/assets/112836415/f5393ebd-5061-4113-ad45-123c78f7ce0a)

2023-05-16 07:46 UTC, shilinlee approved these changes

2023-05-16 07:48 UTC, merged