chore: return the kernel version when ping api
openGemini/openGemini pull request #281
Opened 2023-05-24 03:31 UTC by xmh1011

### What problem does this PR solve?

Issue Number: fix #279 

### What is changed and how it works?
Please describe how it works
```
curl -i -GET 'http://127.0.0.1:8086/ping'
HTTP/1.1 204 No Content
Content-Type: application/json
Request-Id: af2679b8-f9e1-11ed-8001-b6993de84a29
X-Geminidb-Build: OSS
X-Geminidb-Version: v1.0.2
X-Request-Id: af2679b8-f9e1-11ed-8001-b6993de84a29
Date: Wed, 24 May 2023 03:18:41 GMT
```

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B
- [ ] Test cases to be added
- [ ] No code

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-24 03:34 UTC, shilinlee requested changes

2023-05-24 03:34 UTC, shilinlee commented on open_src/influx/httpd/handler.go
> +	version = "v1.0.2"
Maybe use 

https://github.com/openGemini/openGemini/blob/df125d9175ec98695eb4a8de8fe19e1e7677641c/app/ts-sql/main.go#L37

2023-05-29 03:44 UTC, scuzyj commented on app/ts-sql/sql/server.go
> +	s.httpService.Handler.BuildType = "OSS"
what is the meaning of "OSS"?

2023-05-29 03:44 UTC, scuzyj commented on open_src/influx/httpd/handler.go
> +	// Add version and build header to all openGemini requests.
The comments and codes must be consistent. Select either Geminidb or openGemini.

2023-05-29 04:43 UTC, shilinlee commented on app/ts-sql/sql/server.go
> +	s.httpService.Handler.BuildType = "OSS"
**Object Storage Service**

2023-05-29 07:18 UTC, shilinlee approved these changes

2023-05-29 07:19 UTC, merged