feat: ts-monitor supports https and auth
openGemini/openGemini pull request #284
Opened 2023-05-26 06:30 UTC by yehong-z

### What problem does this PR solve?

Issue Number:  #277 

### What is changed and how it works?

ts-monitor supports https and auth

### How Has This Been Tested?

```
[report]
  username = "admin"
  password = "pass"
  https = true
```
Add username and password fields to the report configuration of ts-monitor, which can be used to authenticate against an OpenGemini server that requires authentication. The https field controls whether to use the HTTPS protocol. 

- [ ] Test A
- [ ] Test B
- [ ] Test cases to be added
- [ ] No code

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-27 13:39 UTC, xiangyu5632 commented
Some test cases need to be added please  @yehong-z

2023-05-27 13:41 UTC, xiangyu5632 commented
Please check the checklist in the PR. @yehong-z

2023-05-28 07:29 UTC, shilinlee requested changes

2023-05-28 07:29 UTC, shilinlee commented on lib/config/monitor.go
> +	UseHttps   bool          `toml:"https"`
HTTPSEnabled        bool `toml:"https-enabled"`

2023-05-28 07:29 UTC, shilinlee commented on lib/config/monitor.go
> +	UserName   string        `toml:"username"`
UserName -> Username

2023-05-28 07:29 UTC, shilinlee commented on app/ts-monitor/collector/report.go
> +	protocol := map[bool]string{true: "https", false: "http"}[useHttps]
use this simple way to specify the protocol

``` go
protocol := "http"
if useHttps {
    protocol = "https"
}
```

2023-05-28 07:29 UTC, shilinlee commented on app/ts-monitor/collector/report.go
> +		queryUrl:      fmt.Sprintf("%s://%s/query?u=%s&p=%s", protocol, addr, username, password),
`queryUrl` should not be set protocol and auth, it may not be the same source as `writeUrl`.

2023-05-28 09:34 UTC, shilinlee requested changes

2023-05-28 09:34 UTC, shilinlee commented on config/monitor.conf
> +  # https-enable = true
please change default value to false

2023-05-28 09:53 UTC, shilinlee requested changes

2023-05-28 09:53 UTC, shilinlee commented on config/monitor.conf
> +  # https-enable = false
please change default value to false

2023-05-29 01:54 UTC, shilinlee approved these changes

2023-05-29 01:58 UTC, merged