feat: support for assigning an id to each query and pass it to ts-store
openGemini/openGemini pull request #316
Opened 2023-06-20 07:57 UTC by wtsclwq

### What problem does this PR solve?

Issue Number: fix #291

### What is changed and how it works?

Please describe how it works

Every ts-sql node can assgin different query id for every query, the id range offsets are maintained by ts-meta node in raft

![](https://wtsclwq.oss-cn-beijing.aliyuncs.com/image-20230620155230185.png)

Reference discussion #285

1. ts-sql：

   When ts-sql starts, it interacts with ts-meta by `ExecuteRequestMessage`  to register a query id start offset  for `TaskManager` to assgin query id

2. ts-meta：

   Meta node store a `QueryIDInit`  in its fsm.

   ```go
   const QueryIDSpan 100000
   
   type Data struct {
        ......
       // Query ID range segment allocated by all sql nodes
       QueryIDInit map[string]uint64 // {"127.0.0.1:8086": 0, "127.0.0.2:8086": 10w, "127.0.0.3:8086": 20w}, span is QueryIDSpan
   }
   ```

3. ts-store:

   Get query id and sql.String() from `RemoteQuery`

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B
- [x] Test cases to be added
- [ ] No code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-06-26 03:28 UTC, shilinlee requested changes

2023-06-26 03:28 UTC, shilinlee commented on open_src/influx/query/task_manager.go
> +}
```suggestion
func (t *TaskManager) AssignQueryID() uint64 {
	atomic.CompareAndSwapUint64(&t.nextID, t.queryIDOffset+IdSpan, t.queryIDOffset)
	qid := atomic.AddUint64(&t.nextID, 1)
	return qid
}
```

2023-06-26 03:28 UTC, shilinlee commented on open_src/influx/query/task_manager.go
> +	t.nextID = offset + 1
```suggestion
	t.nextID = offset
```

2023-06-27 08:06 UTC, shilinlee requested changes

2023-06-27 08:30 UTC, shilinlee requested changes

2023-06-27 08:30 UTC, shilinlee commented on open_src/influx/query/task_manager.go
```go
func (t *TaskManager) KillQuery(qid uint64) error {
	t.mu.RLock()
	query := t.queries[qid]
	t.mu.RUnlock()
```

2023-06-27 08:32 UTC, shilinlee requested changes

2023-06-27 08:32 UTC, shilinlee commented on open_src/influx/meta/proto/meta.proto
You can write a README under the folder?

2023-06-27 09:43 UTC, wtsclwq commented on open_src/influx/meta/proto/meta.proto
About what?
1. Instructions for the **commands**?
2. How to modify `.proto` to update `.go`?

2023-06-27 09:46 UTC, shilinlee requested changes

2023-06-27 09:46 UTC, shilinlee commented on lib/metaclient/meta_client.go
> +	err := c.retryUntilExec(proto2.Command_RegisterQueryIDOffsetCommand, proto2.E_RegisterQueryIDOffsetCommand_Command, cmd)
```suggestion
	err := c.retryExec(proto2.Command_RegisterQueryIDOffsetCommand, proto2.E_RegisterQueryIDOffsetCommand_Command, cmd)
```

2023-06-27 09:46 UTC, shilinlee commented on app/ts-meta/meta/store_fsm.go
> +	v := ext.(*proto2.RegisterQueryIDOffsetCommand)
```suggestion
	v, ok := ext.(*proto2.RegisterQueryIDOffsetCommand)
	if !ok {
		panic(fmt.Errorf("%s is not a RegisterQueryIDOffsetCommand", ext))
	}
```

2023-06-27 09:46 UTC, shilinlee commented on open_src/influx/meta/data.go
> +	data.QueryIDInit[host] = nextOffset
Should add a judgment whether the `host` already exists in `QueryIDInit`?

2023-06-27 09:46 UTC, shilinlee commented on open_src/influx/meta/data.go
> +		return errno.NewError(errno.QueryIDOverflow)
`MaxAssignableNum = 1.8446744 * 10^14`
It is impossible to have so many SQLs.
I suggest not adding this `if`

2023-06-27 12:19 UTC, shilinlee requested changes

2023-06-27 12:19 UTC, shilinlee commented on open_src/influx/query/executor.go
> +	ErrQueryIDExhausted = errors.New("query id exhausted")
Do we need this error?

2023-06-30 09:06 UTC, shilinlee requested changes

2023-06-30 14:05 UTC, shilinlee requested changes

2023-06-30 14:05 UTC, shilinlee commented on lib/metaclient/meta_client_test.go
Too long to run this test case. It should less than 5s.

2023-06-30 14:30 UTC, shilinlee requested changes

2023-07-01 05:32 UTC, shilinlee requested changes

2023-07-03 07:45 UTC, shilinlee approved these changes

2023-07-11 15:01 UTC, closed without merging