feat: support log store, log retrieval and add high series cardinality engine
openGemini/openGemini pull request #334
Opened 2023-07-06 07:54 UTC by xiangyu5632

### What problem does this PR solve?

1. Support log data storage and retrieval.
When you use openGemini to store log data, Log data also use line protocol to write, but full-text indexes need to be created on text columns. Log retrieval supports exact match, phrase match, and fuzzy match.
2. Add high series cardinality storage engines (HSCE).
This new storage engine is mainly used to solve the problem of high series cardinality. when you use the HSCE engine and no longer have the upper limit of the time series.
4. The GC is optimized to improve the query performance by 20% to 30%.
5. Fixed some kernel bugs.

### What is changed and how it works?
### **for log**

- Create full-text index: 
`CREATE MEASUREMENT mst_name WITH INDEXTYPE TEXT INDEXLIST field_name1,field_name2`
- Phrase query: 
`SELECT * FROM mst_name WHERE MATCHPHRASE(field_name1, 'GET images backnews.gif')`
- Match query: 
`SELECT * FROM mst_name WHERE MATCH(field_name1, "flashed_stage1.htm")`
- Fuzzy query: 
`SELECT * FROM mst_name WHERE field_name1 LIKE 'flashed_stage1%'`

### **for HSCE**

- Create table like this: 
`CREATE MEASUREMENT rtt2 (campus STRING TAG DEFAULT "", direction STRING TAG DEFAULT "",rtt INT FIELD DEFAULT 0, time INT FIELD DEFAULT 0,) WITH ENGINETYPE = columnstore SHARDKEY campus TYPE hash PRIMARYKEY time SORTKEY time`
- Write data like this: 
`insert rtt2,campus="Shanghai",direction="out" rtt=420i 1673832600000000000
`
### How Has This Been Tested?
`make gotest`
or 
`sh script ut_test.sh`
# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-07-06 10:38 UTC, shilinlee requested changes

2023-07-06 13:35 UTC, xiangyu5632 commented
fgderffg

2023-07-06 13:36 UTC, xiangyu5632 commented
adssfadsf

2023-07-08 03:01 UTC, shilinlee approved these changes

2023-07-08 03:10 UTC, vicky-run approved these changes

2023-07-08 03:16 UTC, merged