Cq develop
openGemini/openGemini pull request #342
Opened 2023-07-12 05:08 UTC by Benevor

### What problem does this PR solve?

Issue Number: close #308

### What is changed and how it works?
Implement `GetCoutinuousQueryLease` RPC message. In CQ service, every time the `handle()` is called, the lease needs to be updated first. When ts-meta processes the first getlease request of ts-sql, all cq tasks should be treated as responses, rather than just responding to changing tasks.
In this scheme, only when creating a cq, deleting a cq, adding a new ts-sql, and ts-sql fails to heartbeat for a long time, the cq scheduling is triggered.

### How Has This Been Tested?

- [x] Test cases to be added

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-14 12:02 UTC, shilinlee commented on app/ts-meta/meta/sql_node_info.go
> +	Cqs map[string]string
```suggestion
	RunningCqs map[string]string
```

2023-08-14 12:09 UTC, shilinlee commented on app/ts-meta/meta/store.go
> +	s.sqlMu.Lock()
The write lock scope is too broad.

2023-08-14 12:12 UTC, shilinlee commented on app/ts-meta/meta/store.go
>  	sqlMu             sync.RWMutex            // concurrency for heartbeat processing and crash detection
Please check the granularity of the lock.

2023-08-14 12:28 UTC, shilinlee commented on app/ts-meta/meta/store.go
> +	}
```suggestion
        s.SqlNodes[sql].CqInfo.IsNew = false
```

2023-08-14 12:34 UTC, shilinlee commented on app/ts-meta/meta/store.go
> +func (s *Store) findSqlByCq(cq string) {
```suggestion
func (s *Store) assignCQ2SQL(cq string) {
```

2023-08-14 12:41 UTC, shilinlee commented on app/ts-meta/meta/store.go
> +	Cq2Sql            map[string]string
```suggestion
	Cq2Sql            map[string]string // {"select * into ...": "127.0.0.1:8086"}
```

2023-08-14 12:48 UTC, shilinlee commented on app/ts-meta/meta/store.go
> +	num := 0
```suggestion
	var sql string
	var minLoad = math.MaxInt
```

2023-08-15 12:24 UTC, shilinlee requested changes

2023-08-15 12:24 UTC, shilinlee commented on lib/metaclient/meta_client.go
> +		panic(err)
What does this code snippet do?

2023-08-16 07:02 UTC, shilinlee requested changes

2023-08-16 07:02 UTC, shilinlee commented on app/ts-meta/meta/store.go
> +	// Cq2Sql            map[string]string       // {"select * into ...": "127.0.0.1:8086"}
```suggestion
```

2023-08-16 07:52 UTC, Benevor commented on lib/metaclient/meta_client.go
> +		panic(err)
I have deleted this code.

2023-08-16 07:52 UTC, Benevor commented on app/ts-meta/meta/message/message.codec.gen.go
> +	return buf, err
I have fixed it.

2023-08-16 07:52 UTC, Benevor commented on app/ts-meta/meta/message/message.codec.gen.go
> +	return err
I have fixed it.

2023-08-16 07:52 UTC, Benevor commented on app/ts-meta/meta/store.go
> +	// Cq2Sql            map[string]string       // {"select * into ...": "127.0.0.1:8086"}
I have fixed it.

2023-09-01 09:15 UTC, merged