feat: support query manager
openGemini/openGemini pull request #347
Opened 2023-07-13 10:21 UTC by wtsclwq

### What problem does this PR solve?

Discussion #285
### What is changed and how it works?

Merge query manager features

![image-20230713145140077](https://wtsclwq.oss-cn-beijing.aliyuncs.com/image-20230713145140077.png)

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B
- [x] Test cases to be added
- [ ] No code

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-07-13 12:39 UTC, shilinlee requested changes

2023-07-13 12:39 UTC, shilinlee commented on open_src/influx/influxql/internal/internal.pb.go
> -	proto.RegisterType((*Measurement)(nil), "influxql.Measurement")
Here is the generated code.

2023-07-13 12:40 UTC, shilinlee requested changes

2023-07-13 12:40 UTC, shilinlee commented on lib/metaclient/meta_callback.go
Please add some unit tests.

2023-07-14 09:25 UTC, shilinlee requested changes

2023-07-14 09:25 UTC, shilinlee commented on app/ts-store/transport/handler/handlers_process.go
> +		err.SetMessage(fmt.Sprintf("the query %d is not running on this store node", qid))
1. define error code in `lib/errno/code.go`
2. define error message in `lib/errno/message.go`
3. e.g. `errno.NewError(errno.ErrQueryNotFound, qid)`

2023-07-14 09:25 UTC, shilinlee commented on app/ts-store/transport/handler/handlers_process.go
> +		err = err.SetErrno(errno.ErrKillQueryFail)
The same as above.

2023-07-14 09:25 UTC, shilinlee commented on app/ts-store/transport/handler/handlers_process.go
> +	isAborted := false
```suggestion
	var isExist bool
	var isAborted bool
```

2023-07-14 09:25 UTC, shilinlee commented on lib/errno/code.go
> +	ErrKillQueryFail             = 1123
add error message in `lib/errno/message.go`

2023-07-14 09:25 UTC, shilinlee commented on open_src/influx/meta/errors.go
> +	ErrKillNotExistentQuery = errors.New("the query %d is not running on any store node")
```suggestion
```

move to `lib/errno/message.go`

2023-07-14 09:30 UTC, shilinlee commented on open_src/influx/query/executor.go
> +	ErrQueryIDOffsetNotInit = errors.New("query id offset has not been initialized, please try again")
unused code

```suggestion
```

2023-07-14 14:01 UTC, shilinlee requested changes

2023-07-14 14:01 UTC, shilinlee commented on lib/errno/message.go
> +	ErrQueryNotFound:             newWarnMessage("query %d is not running on this store node", ModuleQueryEngine),
```suggestion
	ErrQueryNotFound:             newWarnMessage("no such query id: %d", ModuleQueryEngine),
```

2023-07-17 01:28 UTC, shilinlee requested changes

2023-07-17 08:37 UTC, shilinlee approved these changes

2023-07-17 09:23 UTC, scuzyj approved these changes

2023-07-17 09:25 UTC, merged