feat: support to switch leader for meta node
openGemini/openGemini pull request #351
Opened 2023-07-18 06:25 UTC by qwangry

### What problem does this PR solve?
support to switch leader for meta node and it will switch leader by command:

```
curl -i -X POST http://127.0.0.1:8091/leadershiptransfer
```

Issue Number: resolve #346 

### What is changed and how it works?
The leader node executes the appropriate commands.

```
curl -i -X POST http://leader_addr:port/leadershiptransfer
```

### How Has This Been Tested?

```
>curl -i -X POST http://127.0.0.3:8091/leadershiptransfer
HTTP/1.1 307 Temporary Redirect
Location: http://127.0.0.1:8088/leadershiptransfer
Date: Tue, 18 Jul 2023 06:14:29 GMT
Content-Length: 0

>curl -s -GET http://127.0.0.2:8091/debug?witch=raft-stat -H 'all:y' | python -mjson.tool
{
    "127.0.0.2:8091": {
        "applied_index": "57",
        "commit_index": "57",
        "fsm_pending": "0",
        "last_contact": "13.1074ms",
        "last_log_index": "57",
        "last_log_term": "28",
        "last_snapshot_index": "0",
        "last_snapshot_term": "0",
        "latest_configuration": "[{Suffrage:Voter ID:127.0.0.3:8088 Address:127.0.0.3:8088} {Suffrage:Voter ID:127.0.0.1:8088 Address:127.0.0.1:8088} {Suffrage:Voter ID:127.0.0.2:8088 Address:127.0.0.2:8088}]",
        "latest_configuration_index": "0",
        "num_peers": "2",
        "protocol_version": "3",
        "protocol_version_max": "3",
        "protocol_version_min": "0",
        "snapshot_version_max": "1",
        "snapshot_version_min": "0",
        "state": "Follower",
        "term": "28"
    }
}
>curl -s -GET http://127.0.0.1:8091/debug?witch=raft-stat -H 'all:y' | python -mjson.tool
{
    "127.0.0.1:8091": {
        "applied_index": "57",
        "commit_index": "57",
        "fsm_pending": "0",
        "last_contact": "0",
        "last_log_index": "57",
        "last_log_term": "28",
        "last_snapshot_index": "0",
        "last_snapshot_term": "0",
        "latest_configuration": "[{Suffrage:Voter ID:127.0.0.3:8088 Address:127.0.0.3:8088} {Suffrage:Voter ID:127.0.0.1:8088 Address:127.0.0.1:8088} {Suffrage:Voter ID:127.0.0.2:8088 Address:127.0.0.2:8088}]",
        "latest_configuration_index": "0",
        "num_peers": "2",
        "protocol_version": "3",
        "protocol_version_max": "3",
        "protocol_version_min": "0",
        "snapshot_version_max": "1",
        "snapshot_version_min": "0",
        "state": "Leader",
        "term": "28"
    }
}

>curl -s -GET http://127.0.0.3:8091/debug?witch=raft-stat -H 'all:y' | python -mjson.tool
{
    "127.0.0.3:8091": {
        "applied_index": "57",
        "commit_index": "57",
        "fsm_pending": "0",
        "last_contact": "35.8165ms",
        "last_log_index": "57",
        "last_log_term": "28",
        "last_snapshot_index": "0",
        "last_snapshot_term": "0",
        "latest_configuration": "[{Suffrage:Voter ID:127.0.0.3:8088 Address:127.0.0.3:8088} {Suffrage:Voter ID:127.0.0.1:8088 Address:127.0.0.1:8088} {Suffrage:Voter ID:127.0.0.2:8088 Address:127.0.0.2:8088}]",
        "latest_configuration_index": "0",
        "num_peers": "2",
        "protocol_version": "3",
        "protocol_version_max": "3",
        "protocol_version_min": "0",
        "snapshot_version_max": "1",
        "snapshot_version_min": "0",
        "state": "Follower",
        "term": "28"
    }
}
```

When a leader executes this command, it returns that it is a leader and also switches leader
```
>curl -i -X POST http://127.0.0.1:8091/leadershiptransfer
HTTP/1.1 200 OK
Date: Tue, 18 Jul 2023 06:15:10 GMT
Content-Length: 23
Content-Type: text/plain; charset=utf-8

{"OK":true,"Index":48}
>curl -s -GET http://127.0.0.3:8091/debug?witch=raft-stat -H 'all:y' | python -mjson.tool
{
    "127.0.0.3:8091": {
        "applied_index": "58",
        "commit_index": "58",
        "fsm_pending": "0",
        "last_contact": "0",
        "last_log_index": "58",
        "last_log_term": "29",
        "last_snapshot_index": "0",
        "last_snapshot_term": "0",
        "latest_configuration": "[{Suffrage:Voter ID:127.0.0.3:8088 Address:127.0.0.3:8088} {Suffrage:Voter ID:127.0.0.1:8088 Address:127.0.0.1:8088} {Suffrage:Voter ID:127.0.0.2:8088 Address:127.0.0.2:8088}]",
        "latest_configuration_index": "0",
        "num_peers": "2",
        "protocol_version": "3",
        "protocol_version_max": "3",
        "protocol_version_min": "0",
        "snapshot_version_max": "1",
        "snapshot_version_min": "0",
        "state": "Leader",
        "term": "29"
    }
}

>curl -s -GET http://127.0.0.1:8091/debug?witch=raft-stat -H 'all:y' | python -mjson.tool
{
    "127.0.0.1:8091": {
        "applied_index": "58",
        "commit_index": "58",
        "fsm_pending": "0",
        "last_contact": "13.7639ms",
        "last_log_index": "58",
        "last_log_term": "29",
        "last_snapshot_index": "0",
        "last_snapshot_term": "0",
        "latest_configuration": "[{Suffrage:Voter ID:127.0.0.3:8088 Address:127.0.0.3:8088} {Suffrage:Voter ID:127.0.0.1:8088 Address:127.0.0.1:8088} {Suffrage:Voter ID:127.0.0.2:8088 Address:127.0.0.2:8088}]",
        "latest_configuration_index": "0",
        "num_peers": "2",
        "protocol_version": "3",
        "protocol_version_max": "3",
        "protocol_version_min": "0",
        "snapshot_version_max": "1",
        "snapshot_version_min": "0",
        "state": "Follower",
        "term": "29"
    }
}
>curl -s -GET http://127.0.0.2:8091/debug?witch=raft-stat -H 'all:y' | python -mjson.tool
{
    "127.0.0.2:8091": {
        "applied_index": "58",
        "commit_index": "58",
        "fsm_pending": "0",
        "last_contact": "2.5149ms",
        "last_log_index": "58",
        "last_log_term": "29",
        "last_snapshot_index": "0",
        "last_snapshot_term": "0",
        "latest_configuration": "[{Suffrage:Voter ID:127.0.0.3:8088 Address:127.0.0.3:8088} {Suffrage:Voter ID:127.0.0.1:8088 Address:127.0.0.1:8088} {Suffrage:Voter ID:127.0.0.2:8088 Address:127.0.0.2:8088}]",
        "latest_configuration_index": "0",
        "num_peers": "2",
        "protocol_version": "3",
        "protocol_version_max": "3",
        "protocol_version_min": "0",
        "snapshot_version_max": "1",
        "snapshot_version_min": "0",
        "state": "Follower",
        "term": "29"
    }
}
```

# Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2023-07-25 01:08 UTC, scuzyj commented on app/ts-meta/meta/handler.go
> +	"github.com/hashicorp/raft"
need use the raft package in meta？

2023-07-25 09:27 UTC, ready-gogogo commented on app/ts-meta/meta/handler.go
> +			h.httpErr(errors.New("no raft leader"), w, http.StatusServiceUnavailable)
Does it mean this is not raft leader and you need execute this command on leader? Please check it and return more exact error message.

2023-07-25 09:39 UTC, ready-gogogo commented on app/ts-meta/meta/raft_wrapper.go
> +	if !r.IsLeader() {
It is not necessary to judge whether it is a leader, because LeadershipTransfer can only execute on leader successfully.

2023-07-25 10:53 UTC, shilinlee commented
Add this to document. 
https://docs.opengemini.org/guide/manage/syscontrl_cmd.html

2023-07-25 14:55 UTC, shilinlee requested changes

2023-07-25 14:55 UTC, shilinlee commented on app/ts-meta/meta/store.go
> +	if s.raft.State().String() == "Unknown" {
```suggestion
	if s.raft == nil {
```

2023-07-25 14:56 UTC, shilinlee requested changes

2023-07-25 14:56 UTC, shilinlee commented on app/ts-meta/meta/handler.go
> +	if err == raft.ErrNotLeader {
```suggestion
	if err != nil && strings.Contains(err.Error(), "node is not the leader") {
```

2023-07-26 02:51 UTC, shilinlee approved these changes

2023-07-26 03:07 UTC, scuzyj approved these changes

2023-07-26 03:10 UTC, ready-gogogo approved these changes

2023-07-26 03:14 UTC, merged