feat: support show log level config by DDL
openGemini/openGemini pull request #403
Opened 2023-09-30 15:22 UTC by xmh1011

### What problem does this PR solve?

Issue Number: resolve #354 
### What is changed and how it works?
Please describe how it works
Support `SHOW CONFIGS` command.
<img width="1094" alt="image" src="https://github.com/openGemini/openGemini/assets/88817514/2e219874-1e73-47b8-a141-659c4a8983b8">

### How Has This Been Tested?
Add unit test case in lib/config/config_test.go
Add integration test case in tests/server_test.go

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

You can run as follows:
```shell
ts-server
```
```shell
 URL=http://127.0.0.1:8086 go test -mod=mod -test.parallel 1 -timeout 10m ./tests -run  TestServer_ConfigCommand -v GOCACHE=off
```
<img width="1758" alt="image" src="https://github.com/openGemini/openGemini/assets/88817514/9fd4ad54-5cdd-4cb4-8f30-71e0f5545837">

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-07 03:07 UTC, xiangyu5632 approved these changes

2023-10-08 07:54 UTC, shilinlee requested changes

2023-10-08 07:54 UTC, shilinlee commented on tests/server_suite.go
> +				// exp:     `{"results":[{"statement_id":0,"series":[{"columns":["component","instance","name","value"],"values":[["sql",":8086","logging.level","info"]]}]}]}`,
```suggestion
```

2023-10-08 07:54 UTC, shilinlee commented on tests/server_suite.go
> +				// exp:     `{"results":[{"statement_id":0,"series":[{"columns":["component","instance","name","value"],"values":[["sql",":8086","logging.level","debug"]]}]}]}`,
```suggestion			
```

2023-10-08 07:54 UTC, shilinlee commented on open_src/influx/coordinator/statement_executor.go
> +	row.Values = append(row.Values, []interface{}{sqlConfig, app.BindAddress, loggingLevel, logger.Alevel})
Do not add global variable `app.BindAddress`.

Suggest to add `hostname` to StatementExecutor structure.

The hostname should like:
`hostname := config.CombineDomain(s.config.HTTP.Domain, s.config.HTTP.BindAddress)`

2023-10-08 07:55 UTC, shilinlee commented
Rebase your codes from branch `main`.

2023-10-08 09:49 UTC, xmh1011 commented
> Rebase your codes from branch `main`.

ok

2023-10-08 10:52 UTC, shilinlee approved these changes

2023-10-09 09:19 UTC, scuzyj approved these changes

2023-10-09 09:19 UTC, merged