refactor: refactor ts-cli with cobra
openGemini/openGemini pull request #412
Opened 2023-10-12 12:41 UTC by xmh1011

### What problem does this PR solve?

Issue Number: resolve #297 

### What is changed and how it works?
```
➜  openGemini git:(cobra) ts-cli -h        
2023/10/12 20:40:07 proto: duplicate proto type registered: influxql.Measurements
2023/10/12 20:40:07 proto: duplicate proto type registered: influxql.Measurement
ts-cli is a CLI tool of openGemini. It's compatible with influxdb cli.

Usage:
  ts-cli [flags]
  ts-cli [command]

Available Commands:
  execute     Execute a query
  help        Help about any command
  import      Import data to openGemini.
  interactive Work in interactive mode
  version     Print the version of openGemini CLI.

Flags:
      --database string    Database to connect to openGemini.
  -h, --help               help for ts-cli
      --host string        openGemini host to connect to. (default "localhost")
  -p, --password string    Password to connect to openGemini.
      --port int           openGemini port to connect to. (default 8086)
      --precision string   Precision specifies the format of the timestamp:  rfc3339,h,m,s,ms,u or ns. (default "ns")
      --socket string      openGemini unix domain socket to connect to.
      --ssl                Use https for connecting to openGemini.
      --unsafeSsl          Ignore ssl verification when connecting openGemini by https. (default true)
  -u, --username string    Username to connect to openGemini.

Use "ts-cli [command] --help" for more information about a command.
```

```
➜  openGemini git:(cobra) ts-cli import -h
2023/10/12 20:40:57 proto: duplicate proto type registered: influxql.Measurements
2023/10/12 20:40:57 proto: duplicate proto type registered: influxql.Measurement
Import a previous database export from file.

Usage:
  ts-cli import [flags]

Flags:
  -h, --help               help for import
      --host string        openGemini host to connect to. (default "localhost")
  -p, --password string    Password to connect to openGemini.
      --path string        Path to the file to import.
      --port int           openGemini port to connect to. (default 8086)
      --precision string   Precision specifies the format of the timestamp:  rfc3339,h,m,s,ms,u or ns. (default "ns")
      --ssl                Use https for connecting to openGemini.
  -u, --username string    Username to connect to openGemini.
```

### How Has This Been Tested?

- [ ] Test cases to be added

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-16 12:27 UTC, shilinlee requested changes

2023-10-16 12:27 UTC, shilinlee commented on go.mod
> +	github.com/stretchr/objx v0.4.0 // indirect
```suggestion
```

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/root.go
> +	rootCmd.Flags().StringVar(&options.Host, "host", DEFAULT_HOST, "openGemini host to connect to.")
```suggestion
	rootCmd.Flags().StringVar(&options.Host, "host", DEFAULT_HOST, `ts-sql host to connect to. (default "localhost")`)
```

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/root.go
> +	rootCmd.Flags().IntVar(&options.Port, "port", DEFAULT_PORT, "openGemini port to connect to.")
```suggestion
	rootCmd.Flags().IntVar(&options.Port, "port", DEFAULT_PORT, "ts-sql tcp port to connect to. (default 8086)")
```

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/root.go
> +	rootCmd.Flags().StringVar(&options.Precision, "precision", "ns", "Precision specifies the format of the timestamp:  rfc3339,h,m,s,ms,u or ns.")
```suggestion
	rootCmd.Flags().StringVar(&options.Precision, "precision", "ns", "Specify the format of the timestamp: rfc3339, h, m, s, ms, u or ns. default is ns.")
```

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/root.go
>  		Long:  `ts-cli is a CLI tool of openGemini. It's compatible with influxdb cli.`,
```suggestion
		Long:  `ts-cli is a CLI tool of openGemini.`,
```

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/root.go
> +	rootCmd.Flags().StringVar(&options.Precision, "precision", "ns", "Precision specifies the format of the timestamp:  rfc3339,h,m,s,ms,u or ns.")
Check for sub command `import` also.

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/import.go
> +	Long:  `Import a previous database export from file.`,
```suggestion
	Long:  `Import line protocol text file to openGemini.`,
```

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/version.go
> +const TsStore = "TsCli"
```suggestion
const TsCli = "TsCli"
```

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/version.go
> +	Short: "Print the version of openGemini CLI.",
```suggestion
	Short: "Display the version of openGemini CLI.",
```

2023-10-16 12:27 UTC, shilinlee commented on app/ts-cli/cmd/version.go
> +	Long:  `The version of openGemini CLI. Higher version of openGemini CLI is compatible with lower version of open-Gemini.`,
```suggestion
	Long:  `Display the version of openGemini CLI.`,
```

2023-10-16 12:35 UTC, shilinlee requested changes

2023-10-16 12:35 UTC, shilinlee commented on app/ts-cli/cmd/import.go
> +	Short: "Import data to openGemini.",
```suggestion
	Short: "Import data to openGemini",
```

2023-10-16 23:17 UTC, Shoothzj approved these changes

2023-10-17 04:59 UTC, shilinlee requested changes

2023-10-17 04:59 UTC, shilinlee commented on app/ts-cli/main.go
> -	TsBranch  string
Version info keep at `main` package.

2023-10-17 06:42 UTC, shilinlee approved these changes

2023-10-17 11:14 UTC, scuzyj approved these changes

2023-10-17 11:15 UTC, merged