feat: support show configs by DDL
openGemini/openGemini pull request #413
Opened 2023-10-13 04:24 UTC by xmh1011

### What problem does this PR solve?
<!-- #354 

Please create an issue first to describe the problem.
Issue Number: resolve #354 

### What is changed and how it works?

```
➜  openGemini git:(show-configs) /usr/bin/env bash /Users/xiaominghao/code/openGemini/scripts/install_cluster.sh
ref link:
https://superuser.com/questions/458875/how-do-you-get-loopback-addresses-other-than-127-0-0-1-to-work-on-os-x
temporarily open 127.0.0.2/127.0.0.3 for ts-store/ts-meta, please enter admin pwd:
Password:
➜  openGemini git:(show-configs) ts-cli
2023/10/13 12:22:32 proto: duplicate proto type registered: influxql.Measurements
2023/10/13 12:22:32 proto: duplicate proto type registered: influxql.Measurement
openGemini CLI 0.1.0 (rev-revision)
Please use `quit`, `exit` or `Ctrl-D` to exit this program.
> show configs
+-----------+----------------+----------------------------------------+------------------------------------------------+
| component | instance       | name                                   | value                                          |
+-----------+----------------+----------------------------------------+------------------------------------------------+
| sql       | 127.0.0.1:8086 | logging.level                          | info                                           |
| sql       | 127.0.0.1:8086 | logging.format                         | auto                                           |
| sql       | 127.0.0.1:8086 | logging.max-size                       | 67108864                                       |
| sql       | 127.0.0.1:8086 | logging.max-num                        | 16                                             |
| sql       | 127.0.0.1:8086 | logging.max-age                        | 7                                              |
| sql       | 127.0.0.1:8086 | logging.compress-enabled               | true                                           |
| sql       | 127.0.0.1:8086 | logging.path                           | /tmp/openGemini/logs/1                         |
| sql       | 127.0.0.1:8086 | meta-join                              | [127.0.0.1:8092 127.0.0.2:8092 127.0.0.3:8092] |
| sql       | 127.0.0.1:8086 | ignore-empty-tag                       | false                                          |
| sql       | 127.0.0.1:8086 | report-enable                          | true                                           |
| sql       | 127.0.0.1:8086 | crypto-config                          |                                                |
| sql       | 127.0.0.1:8086 | cluster-id                             |                                                |
| sql       | 127.0.0.1:8086 | cpu-num                                | 0                                              |
| sql       | 127.0.0.1:8086 | read-stop                              | false                                          |
| sql       | 127.0.0.1:8086 | write-stop                             | false                                          |
| sql       | 127.0.0.1:8086 | write-timeout                          | 10s                                            |
| sql       | 127.0.0.1:8086 | memory-size                            | 0                                              |
| sql       | 127.0.0.1:8086 | executor-memory-size-limit             | 0                                              |
| sql       | 127.0.0.1:8086 | executor-memory-wait-time              | 0s                                             |
| sql       | 127.0.0.1:8086 | max-query-mem                          | 0                                              |
| sql       | 127.0.0.1:8086 | select-hash-algorithm                  | ver03                                          |
| sql       | 127.0.0.1:8086 | cpu-allocation-ratio                   | 1                                              |
| sql       | 127.0.0.1:8086 | ha-policy                              | write-available-first                          |
| sql       | 127.0.0.1:8086 | max-concurrent-queries                 | 0                                              |
| sql       | 127.0.0.1:8086 | query-timeout                          | 0s                                             |
| sql       | 127.0.0.1:8086 | query-limit-interval-time              | 10                                             |
| sql       | 127.0.0.1:8086 | query-limit-level                      | 0                                              |
| sql       | 127.0.0.1:8086 | query-limit-flag                       | false                                          |
| sql       | 127.0.0.1:8086 | query-time-compare-enabled             | true                                           |
| sql       | 127.0.0.1:8086 | continuous-query-enabled               | false                                          |
| sql       | 127.0.0.1:8086 | continuous-query-run-interval          | 1s                                             |
| sql       | 127.0.0.1:8086 | continuous-query-max-process-CQ-number | 2                                              |
| sql       | 127.0.0.1:8086 | force-broadcast-query                  | false                                          |
| sql       | 127.0.0.1:8086 | log-queries-after                      | 0s                                             |
| sql       | 127.0.0.1:8086 | shard-writer-timeout                   | 10s                                            |
| sql       | 127.0.0.1:8086 | shard-mapper-timeout                   | 10s                                            |
| sql       | 127.0.0.1:8086 | shard-tier                             | warm                                           |
| sql       | 127.0.0.1:8086 | meta-executor-write-timeout            | 5s                                             |
| sql       | 127.0.0.1:8086 | rp-limit                               | 100                                            |
| sql       | 127.0.0.1:8086 | time-range-limit                       | <nil>                                          |
| sql       | 127.0.0.1:8086 | tag-limit                              | 0                                              |
| sql       | 127.0.0.1:8086 | byte-buffer-pool-default-size          | 0                                              |
| sql       | 127.0.0.1:8086 | recv-window-size                       | 0                                              |
| sql       | 127.0.0.1:8086 | concurrent-accept-session              | 0                                              |
| sql       | 127.0.0.1:8086 | conn-pool-size                         | 0                                              |
| sql       | 127.0.0.1:8086 | open-session-timeout                   | 0s                                             |
| sql       | 127.0.0.1:8086 | session-select-timeout                 | 0s                                             |
| sql       | 127.0.0.1:8086 | tcp-dial-timeout                       | 0s                                             |
| sql       | 127.0.0.1:8086 | data-ack-timeout                       | 0s                                             |
| sql       | 127.0.0.1:8086 | compress-enable                        | false                                          |
| sql       | 127.0.0.1:8086 | tls-enable                             | false                                          |
| sql       | 127.0.0.1:8086 | tls-client-auth                        | false                                          |
| sql       | 127.0.0.1:8086 | tls-insecure-skip-verify               | false                                          |
| sql       | 127.0.0.1:8086 | tls-certificate                        |                                                |
| sql       | 127.0.0.1:8086 | tls-private-key                        |                                                |
| sql       | 127.0.0.1:8086 | tls-client-certificate                 |                                                |
| sql       | 127.0.0.1:8086 | tls-client-priv [...]

2023-10-17 06:30 UTC, shilinlee requested changes

2023-10-17 06:30 UTC, shilinlee commented on tests/server_suite.go
> +				skip:    true,
Why skip this test case?

2023-10-20 06:13 UTC, shilinlee approved these changes

2023-10-20 06:52 UTC, scuzyj approved these changes

2023-10-20 06:52 UTC, merged