feat: support DDL like show cluster status
openGemini/openGemini pull request #453
Opened 2024-01-03 06:21 UTC by xmh1011

### What problem does this PR solve?

Issue Number: resolve #452 

### What is changed and how it works?
Please describe how it works

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B
- [ ] Test cases to be added
- [ ] No code

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-04 05:54 UTC, shilinlee requested changes

2024-01-04 05:54 UTC, shilinlee commented on open_src/influx/meta/data.go
> +	timestamp := time.Now().Unix()
```suggestion
	timestamp := time.Now().UTC().Unix()
```

2024-01-04 05:54 UTC, shilinlee commented on open_src/influx/meta/data.go
> +func (data *Data) ShowClusterStatusWithCondition(nodeType, nodeID string, ID uint64) (models.Rows, error) {
`nodeID` and `ID` is the same thing?

```suggestion
func (data *Data) ShowClusterStatusWithCondition(nodeType string, ID uint64) (models.Rows, error) {
```

2024-01-04 05:54 UTC, shilinlee commented on open_src/influx/meta/data.go
> +	timestamp := time.Now().Unix()
```suggestion
	timestamp := time.Now().UTC().Unix()
```

2024-01-04 05:54 UTC, shilinlee commented on open_src/influx/meta/data.go
> +	}
```suggestion

switch nodeType:
case METANODE:
  data.WalkMetaNodes(func(node *NodeInfo) {
	if ID == 0 || node.ID == ID {
				  row.Values = append(row.Values, []interface{}{timestamp, node.Status, node.Host, node.ID, METANODE})
case DATANODE
  data.WalkDataNodes(func(node *DataNode) {
	if ID == 0 || node.ID == ID {
				  row.Values = append(row.Values, []interface{}{timestamp, node.Status, node.Host, node.ID, DATANODE})
			  }
default:
	data.WalkMetaNodes(func(node *NodeInfo) {
	if ID == 0 ||  node.ID == ID {
				  row.Values = append(row.Values, []interface{}{timestamp, node.Status, node.Host, node.ID, METANODE})		  
	data.WalkDataNodes(func(node *DataNode) {
	if ID == 0 || node.ID == ID {
				  row.Values = append(row.Values, []interface{}{timestamp, node.Status, node.Host, node.ID, DATANODE})
			  }
	
```

2024-01-04 07:31 UTC, shilinlee requested changes

2024-01-04 07:31 UTC, shilinlee commented on open_src/influx/influxql/ast.go
> +}
```suggestion
type ShowClusterStatusStatement struct {
	NodeType string
	NodeID   string
}
```

2024-01-04 07:31 UTC, shilinlee commented on open_src/influx/influxql/sql.y
> +
```suggestion
SHOW_CLUSTER_STATUS_STATEMENT:
    SHOW CLUSTER STATUS WHERE_CLUSTER_CLAUSE
     {
          $$ = $4
     }

WHERE_CLUSTER_CLAUSE:
    WHERE IDENT EQ IDENT
    {
        stmt := &ShowClusterStatusStatement{}
        if strings.ToLower($2) == "nodetype" {
            stmt.NodeType = $4
        } else {
            stmt.NodeID = $4
        }
        $$ = stmt
    }
    |WHERE IDENT EQ IDENT AND IDENT EQ IDENT
    {
        stmt := &ShowClusterStatusStatement{}
        if strings.ToLower($2) == "nodetype" {
            stmt.NodeType = $4
        } else {


            stmt.NodeID = $4
        }
        if strings.ToLower($6) == "nodetype" {
            stmt.NodeType = $8
        } else {
            stmt.NodeID = $8
        }
        $$ = stmt
    }
    |
    {
        $$ = &ShowClusterStatusStatement{}
    }

```

2024-01-04 08:02 UTC, shilinlee requested changes

2024-01-04 08:02 UTC, shilinlee commented on open_src/influx/influxql/sql.y
> +    SHOW CLUSTER STATUS WHERE_CLAUSE
```suggestion
    SHOW CLUSTER WHERE_CLAUSE
```

2024-01-04 12:15 UTC, shilinlee requested changes

2024-01-04 12:26 UTC, shilinlee approved these changes

2024-01-05 01:27 UTC, fx408 approved these changes
ok

2024-01-05 01:33 UTC, scuzyj approved these changes

2024-01-05 01:33 UTC, merged

2024-01-05 01:44 UTC, scuzyj commented
![image](https://github.com/openGemini/openGemini/assets/108262220/5f16daa0-e21e-4213-861d-68af14c0fc1d)
it is better to convert status to a string，because the meanings of numbers cannot be understood.