Feat: support export data
openGemini/openGemini pull request #755
Opened 2024-09-19 15:09 UTC by rumor-sourse

### What problem does this PR solve?

Issue Number: close/fix/resolve/ref #xxx

### What is changed and how it works?
Please describe how it works

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B
- [ ] Test cases to be added
- [ ] No code

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-09-20 00:39 UTC, xuthus5 commented
please rebase your commit.

2024-09-20 01:28 UTC, xuthus5 commented on app/ts-cli/cmd/export.go
> +package cmd
The LICENSE description needs to be added to the file header.

2024-09-20 01:28 UTC, xuthus5 commented on app/ts-cli/cmd/export.go
> +	"github.com/openGemini/openGemini/app/ts-cli/geminicli"
Use `goimports-reviser` to sort packages, such as: `goimports-reviser -project-name none-pjn ./...`

2024-09-20 01:28 UTC, xuthus5 commented on app/ts-cli/cmd/export.go
> +	jsonFile, err := os.Open(geminicli.ResumeJsonPath)
Replace `os.Open` with `os.ReadFile` is a better way to read only the file content.

2024-09-20 01:28 UTC, xuthus5 commented on app/ts-cli/geminicli/export.go
> +	if start != "" {
Replace if-else with default assignment.

2024-09-20 01:46 UTC, xuthus5 commented
Replace title `Feat` to `feat`.

2024-09-20 03:54 UTC, xuthus5 commented on app/ts-cli/geminicli/export.go
> +	sort.Slice(dirs, func(i, j int) bool {
`Sort.Strings` may be more efficient if you only want to take the first or last element of a sorted string slice.

2024-09-20 03:54 UTC, xuthus5 commented on app/ts-cli/geminicli/export.go
> +	dataDir := path.Join(actualDataDir, databaseName)
`path.Join` use unix style slash `/` to combie string, on windows platform may cause problem.

2024-09-20 03:54 UTC, xuthus5 commented on app/ts-cli/geminicli/export.go
> +			rpTsspPath := path.Join(ptTsspPath, retentionPolicy)
We need to examine the path splicing of different OS.

2024-09-20 03:54 UTC, xuthus5 commented on app/ts-cli/geminicli/export.go
> +				d.rpToWalDirMap[ptWithRp] = rpWalPath
If `os.Stat` result is nil, `d.rpToWalDirMap` will not set a value. Is this expected?

2024-09-20 03:54 UTC, xuthus5 commented on app/ts-cli/geminicli/export.go
> +			if rpDir.IsDir() {
Use the guard statement to reduce the if judgment.

2024-09-20 06:08 UTC, xuthus5 commented
We'd better describe how this feature works.

2024-09-20 14:51 UTC, xuthus5 commented on app/ts-cli/cmd/export.go
> +// Copyright 2022 Huawei Cloud Computing Technologies Co., Ltd.
replace copyright year to 2024, you can change author to `openGemini author` like this: `Copyright 2024 The openGemini Authors All rights reserved.`.

2024-09-20 14:54 UTC, xuthus5 commented
If you have resolved any review change, please mark it.

2024-09-21 06:52 UTC, xiangyu5632 commented
Why we need to upgrade go version to go v1.21？

2024-09-21 12:03 UTC, xiangyu5632 commented on app/ts-cli/cmd/export.go
> +// Copyright 2024 Huawei Cloud Computing Technologies Co., Ltd.
openGemini authors

2024-09-21 12:07 UTC, xiangyu5632 commented
> TL;DR please rebase your commit and signed off change. `git commit -s -m "your commit message"`

2024-09-22 12:15 UTC, shilinlee requested changes

2024-09-22 12:15 UTC, shilinlee commented on app/ts-cli/geminicli/export.go
> +	// err
remove the comment

2024-09-22 12:25 UTC, shilinlee requested changes

2024-09-22 12:25 UTC, shilinlee commented on app/ts-cli/tests/export/init.go
> +	//time.Sleep(time.Second * 1)
remove unused code

2024-09-23 06:46 UTC, xiangyu5632 commented
Please re-describe the content of the PR

2024-09-23 10:32 UTC, xuthus5 commented
> 放一个tests目录在 app/ts-cli 下面中感觉怪怪的。如果是功能测试用例，我建议放到AT用例的tests目录下。 cc @shilinlee @xuthus5 @fx408 ，你们觉得呢？

I think it's the better way.

2024-10-21 15:31 UTC, xuthus5 commented
The evolution strategy of ts-cli will be discussed at the community meeting in October, and this submission is temporarily suspended.

2024-10-26 11:36 UTC, shilinlee commented
> The evolution strategy of `ts-cli` will be discussed at the community meeting in October, and this submission is temporarily suspended.↳

This feature has been fully tested and there is no problem in merging it into the feature branch.

2024-10-26 11:38 UTC, shilinlee approved these changes
LGTM

2024-10-26 11:38 UTC, merged