chore: remove error returning and make ColVal codec bound to little endian in record codec methods
openGemini/openGemini pull request #822
Opened 2024-12-27 06:35 UTC by StepY1aoZz

### What problem does this PR solve?

red #816 

### What is changed and how it works?
This PR remove unnecessary error returning in record marshal and unmarshal methods and make AppendUint32Slice bound to little endian.

Considering most machine running openGemini now is little endian, use little endian in AppendUint32Slice may bring us most compatibility.

2024-12-27 07:06 UTC, shoothzj requested changes
I don't think it's a `chore`

2024-12-27 07:20 UTC, StepY1aoZz commented
> I don't think it's a `chore`

is using `refactor` instead better?

2024-12-27 07:27 UTC, shoothzj commented
@StepY1aoZz If you change the behavior of software, it definitely should be feat or fix

2024-12-27 08:17 UTC, StepY1aoZz commented
> @StepY1aoZz If you change the behavior of software, it definitely should be feat or fix

Got it. Thanks!

2024-12-28 09:09 UTC, fx408 approved these changes

2024-12-30 01:41 UTC, merged